export const options = [
  { value: 'blockchain', label: 'Blockchain' },
  { value: 'python', label: 'Python' },
  { value: 'sql', label: 'SQL' },
  { value: 'machine-learning', label: 'Machine Learning' },
  { value: 'hTML/CSS', label: 'HTML/CSS' },
  { value: 'javaScript', label: 'JavaScript' },
  { value: 'typeScript', label: 'TypeScript' },
  { value: 'react', label: 'React' },
  { value: 'angular', label: 'Angular' },
  { value: 'node.js', label: 'Node.js' },
  { value: 'java', label: 'Java' },
  { value: 'linus', label: 'Linus' },
  { value: 'xml', label: 'XML' },
  { value: 'C++', label: 'C++' },
  { value: 'C#', label: 'C#' },
  { value: 'php', label: 'PHP' },
  { value: 'iOS/Swift', label: 'iOS/Swift' },
  { value: 'ruby/Rails', label: 'Ruby/Rails' }
];
